name: Conway

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Update rustup
      run: rustup self update
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install 1.87
        rustup default 1.87
    - name: Install Clippy
      run: rustup component add clippy
    - name: Install rustfmt
      run: rustup component add rustfmt

    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --color always --all-features
